name: validate-apex-code
on: [push]
jobs:
  check-apex:
    runs-on: ubuntu-latest
    steps:
      - name: Check APEX pmd rules
        uses: legetz/setup-pmd@v6.48
      - run: pmd -language apex --dir . --rulesets ./pmd-rules.xml -f text

    steps:
      - name: Apex design
        uses: legetz/setup-pmd@v6.48
      - run: pmd --dir ./force-app/main/default/classes -R category/apex/design.xml -f text

